name: Trivy Image Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t python-samples-fastapi-restful .

      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.16.1
        with:
          version: latest

      - name: Run Trivy scan (como en Windows)
        run: trivy image --no-progress --format table -o trivy-report.txt python-samples-fastapi-restful

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt
