name: Docker Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan:
    name: Scan Docker Image with Anchore
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t python-samples-fastapi-restful .

      - name: Run Anchore scan
        uses: anchore/scan-action@v2
        with:
          image-reference: python-samples-fastapi-restful
          fail-build: true
